#!/usr/bin/env bash
# Render terraform/terraform.tfvars from .env, keeping .env the single source
# of truth for the whole deployment.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

require_env_file

TFVARS="$REPO_ROOT/terraform/terraform.tfvars"

# Escape backslashes and double quotes for HCL string literals.
hcl_string() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

docker_host="${DOCKER_HOST:-unix:///var/run/docker.sock}"

cat >"$TFVARS" <<EOF
# GENERATED by scripts/env-to-tfvars.sh -- edit .env instead.
docker_host          = $(hcl_string "$docker_host")
network_name         = $(hcl_string "$(env_get DOCKER_NETWORK llm-assistant-net)")
model_cache_volume   = $(hcl_string "$(env_get MODEL_CACHE_VOLUME llm-assistant-model-cache)")
model_id             = $(hcl_string "$(env_get MODEL_ID)")
tensor_parallel_size = $(env_get TENSOR_PARALLEL_SIZE 2)
project_dir          = $(hcl_string "$REPO_ROOT")
EOF

ok "wrote terraform/terraform.tfvars"
